@TodoApi_HostAddress = http://localhost:5064

GET {{TodoApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TodoApi_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "todo",
  "description": "Detta är en todon",
  "isComplete": false,
  "secret": ""
}

###

GET {{TodoApi_HostAddress}}/api/todoitems

###

GET {{TodoApi_HostAddress}}/api/todoitems/{c4c84832-7d9a-4dc8-9923-df614f6ea466}

###

PUT {{TodoApi_HostAddress}}/api/todoitems/toggle-status/{e906c382-4735-4b84-bc0c-2fc7fa0042be}

###
